# Generated by Django 2.0.4 on 2018-05-04 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EaAcademicHistory',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('university', models.CharField(max_length=255)),
                ('year_of_passing', models.DateField()),
                ('percentage_scored', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'ea_academic_history',
            },
        ),
        migrations.CreateModel(
            name='EaAttendance',
            fields=[
                ('att_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user_type', models.CharField(max_length=255)),
                ('attend_status', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'ea_attendance',
            },
        ),
        migrations.CreateModel(
            name='EaStudentDetails',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('standard', models.PositiveSmallIntegerField()),
                ('school', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('emergency_number', models.BigIntegerField()),
                ('roll_no', models.IntegerField()),
                ('year_of_joining', models.DateTimeField()),
                ('birthdate', models.DateField()),
                ('contact_no', models.BigIntegerField()),
                ('refs', models.TextField()),
                ('fees_paid', models.IntegerField()),
                ('subjects_enrolled', models.TextField()),
                ('activated_status', models.BooleanField()),
                ('year_of_leaving', models.DateTimeField()),
                ('stream', models.CharField(max_length=255)),
                ('board', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'ea_student_details',
            },
        ),
        migrations.CreateModel(
            name='EaTeacherDetails',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('standard', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('year_of_joining', models.DateTimeField()),
                ('activated_status', models.BooleanField()),
                ('contact_no', models.BigIntegerField()),
                ('salary', models.IntegerField()),
                ('bank_details', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'ea_teacher_details',
            },
        ),
        migrations.CreateModel(
            name='EaUserMapping',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'ea_user_mapping',
            },
        ),
    ]
