# Generated by Django 2.0.4 on 2018-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eanewscomments_eanewsfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EaFeesAccounts',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('paid_status', models.BooleanField(default=False)),
                ('fees_paid', models.IntegerField(blank=True)),
                ('total_fees', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'ea_fees_accounts',
                'managed': False,
            },
        ),
    ]
